### ISSUE TITLE
Please make a compile-option that has libxo just become printf()s

### ISSUE THREAD

**Issue by erikarn** [Juniper/libxo#12]
Hi!
For (very) embedded applications we absolutely don't need any of the libxo plumbing for spitting out XML, JSON, etc. We may also not need it for smaller footprint builds like the rescue image builds.

Would it be possible/OK to have a version of libxo's API that just becomes printf()s?

**Comment by philshafer** [comment]
Fixed in develop; compiling with LIBXO_TEXT_ONLY will remove (via C optimizer) the generation of other formats.
