### ISSUE TITLE
xo_emit(3) in FreeBSD points to github page for manual and is not versioned appropriately; can diverge from source code

### ISSUE THREAD

**Issue by yaneurabeya** [Juniper/libxo#13]
xo_emit(3) on FreeBSD points the reader to the github manual instead of providing a description of the lexicon, or an in-depth description of the APIs. The problem with this is that one day when libxo has matured enough in FreeBSD, and the libxo project has been under development long enough, the manual will diverge from the source code.

The documentation needs to be versioned appropriately, or needs to be distributed with FreeBSD and needs to reference appropriate paths under /usr/share/doc/... .

**Comment by philshafer** [comment]
[Strange; I thought I'd commented on this one, but it's not here]

Anyway, the current state is that I now publish the docs in a version-specific way on github:

http://juniper.github.io/libxo/0.3.2/libxo-manual.html

And the version-less string points to the most-recent version.

Where I'm stuck is how to get this into the man pages.

I can use autotools to make libxo.3.in and subst the version in at configure time.  Or I can make a token (CURRENT_VERSION) that gets substituted at install time.  I'm indecisive re: which will cause less pain, but will likely to with the former.

Thanks,
 Phil

**Comment by philshafer** [comment]
Perhaps a better alternative:

I could move the trailing "Additional Documentation" section to a single libxo.ref.3.in file and do the substitution in that single file.  Then ".so" that file in all the various .[135] files.  I don't see a good precedent for this, but there are numerous man files that contain a single .so statement, but no pages that have content plus any .so statements.  Still seems better than .in'ing all man pages.

Thanks,
 Phil

**Comment by yaneurabeya** [comment]
Perhaps. There might also be some macros that can be used to simplify referencing all of the necessary manpages

**Comment by philshafer** [comment]
Could you please point me to an example?

Thanks,
 Phil

**Comment by philshafer** [comment]
I've noddled with ".so" and could not get success.  Any other ideas?

Thanks,
 Phil

**Comment by philshafer** [comment]
Ended up adding an install-data-hook to append "add.man" content that configure builds from add.man.in with the proper version info.

fixed in libxo-0.4.2
