### ISSUE TITLE
Padding {P:} option can't take zero length string.

### ISSUE THREAD

**Issue by splbio** [Juniper/libxo#14]
It seems like the following code will cause libxo to walk off the end of an array:

```
xo_emit("{P:}");
```

This ha something to do with it not accepting a zero length string for the 'P' (padding) modifier.

This causes some difficult to track down bugs due to what appears to be stack smashing.

Besides this bug, what this means that for potentially zero pads, you need additional logic.  See the following workaround:

https://github.com/splbio/freebsd/commit/31a2ccd9a7008a1190279c1e2f689f438fc46619

**Comment by philshafer** [comment]
Fixed.
