### ISSUE TITLE
Padding {P:} option can't take integer padding argument.

### ISSUE THREAD

**Issue by splbio** [Juniper/libxo#15]
Following the documentation I was unable to get the Padding {P:} option to take an integer argument.

Example of what should work:

```
xo_emit("{P:/30s}");
```
This example is given in the docs here:
http://juniper.github.io/libxo/libxo-manual.html#the-padding-role-p

However this does not appear to work.

Because this does not seem to work in the version in FreeBSD, the following workaround is needed:

https://github.com/splbio/freebsd/commit/31a2ccd9a7008a1190279c1e2f689f438fc46619

**Comment by philshafer** [comment]
This is a typo in the documentation.  I missed the "%" in the format string:

xo_emit("{P:/%30s}", "");

With "{P:}", you can either give a static string or a format after the "/".  The "{P:/30s}" was writing a literal "30s" which when likely muffed the remaining arguments.  I'll fix the docs.

Thanks,
 Phil

**Comment by splbio** [comment]
I don't think that just "{P:}" without spaces works that needs to be fixed as well. 

For instance "{P:       }" is fine but "{P:}" will cause segfault.

**Comment by philshafer** [comment]
Ah, that’s what the other issue meant.  Will fix.  Thanks….

**Comment by philshafer** [comment]
Fixed in 'develop'
