### ISSUE TITLE
Feature request: Simplify definition of lists (omit need for explicit state in calling programs)

### ISSUE THREAD

**Issue by stesser** [Juniper/libxo#16]
The functions xo_open_list() and xo_close_list() are only required for JSON and ignored for all other formats. 

For well-formed JSON output, xo_open_list("tag") must be executed immediately before the first xo_open_instance("tag") and xo_close_list("tag") must follow the last xo_open_instance("tag").
Experience shows, that correct emission of xo_open/close_list() for optional lists requires explicit state variables and thus complicates the program code and creates significant effort to get tested and correct.

For examples of the complexity see the conditional xo_open_list() calls in https://reviews.freebsd.org/D1206 (pciconf) and https://reviews.freebsd.org/D1380 (netstat).

Both xo_open_list() and xo_close_list() can be automatically emitted, though:
- xo_open_instance("tag") could check whether a list of the same name has already been opened and shall call xo_open_list("tag") if not.
- Any xo_open_container(), xo_open_instance(), xo_emit() for a different tag needs to implicitly call xo_close_list("list_tag") to close the list, before a new node is generated for a tag not belonging into the list.  The same is true when the enclosing element is closed.
- Both xo_open_list() and xo_close_list() will continue to work and behave as before, but they need to maintain the state required for the automatic calls to these two functions as outlined above.  This state consists of the name of the current list (parameter to xo_open_list()) and the information whether an list element has already been created with xo_open_instance() or xo_emit().

One effect of having "xo_open_list()" in a program is, that empty JSON arrays will be generated, if there is not a single xo_open_instance() for this list.  This differs from XML output, where the xo_open_list() does not generate any output and lack of xo_open_instance() means, than no XML element will be emitted at all.  If the empty JSON array is preferred, then use of xo_open_list() preserves this behaviour.

Not directly related but when the implicit xo_open_list() is implememted, it is just a minor modification:
xo_emit("{:tag/...}") within xo_open_list("tag") should generate the same output as if the "l" modifier was present (only for tags that are identical in xo_emit() and xo_open_list()).

To better warn in case of multiple lists with identical names being the child of one node, a new warning feature should be implemented: If a list has been closed (implicitly or explicitly), then any new xo_open_list for the same tag should emit a warning: In XML format, the lists will be considered to consinst of the concatenation of all elements. In JSON format, only the last list will be effective and all elements in any earlier list of the same name will be lost.

This situation is already an error when using the current API (which requires explicit xo_open/close_list() calls), and a warning should be generated for it.

**Comment by philshafer** [comment]
Fixed (auto state transitions and markers) in develop.
