### ISSUE TITLE
Fix bug in xo_warn_c()

### ISSUE THREAD

**Issue by stesser** [Juniper/libxo#18]
The xo_warn_c function calls xo_warn_hcv() with mis-ordered arguments:

xo_warn_hcv(NULL, 0, code, fmt, vap) should be xo_warn_hcv(NULL, code, 0, fmt, vap)

```
Index: libxo.c
===================================================================
--- libxo.c     (revision 276665)
+++ libxo.c     (working copy)
@@ -1027,7 +1033,7 @@
     va_list vap;

     va_start(vap, fmt);
-    xo_warn_hcv(NULL, 0, code, fmt, vap);
+    xo_warn_hcv(NULL, code, 0, fmt, vap);
     va_end(vap);
 }
```

**Comment by philshafer** [comment]
Yup, this fix is already in the “develop” branch and will be in the next release, which should be out shortly.

Thanks,
 Phil

**Comment by philshafer** [comment]
Merge into develop
