### ISSUE TITLE
releases don't include manpages

### ISSUE THREAD

**Issue by brooksdavis** [Juniper/libxo#24]
Release tarballs have makefiles that reference manpages and they exist in the repository, but the manpages themselves are in the tarballs so the release don't build without patching.

**Comment by philshafer** [comment]
Got it.  Will fix.  Thanks…

**Comment by philshafer** [comment]
Just an update: I’ve 1/2 fixed this, in that I now make versioned manual pages on github, but making the man pages point at the specific version means using .in files for the man page sources.  I need to finish that 1/2.

Thanks,
 Phil

**Comment by philshafer** [comment]
Ooops.  Upgrade here was for another issue.  This issue is fixed in develop.

**Comment by philshafer** [comment]
So I’m now publishing version content on github.io, like:

http://juniper.github.io/libxo/0.3.2/libxo-manual.html <http://juniper.github.io/libxo/0.3.2/libxo-manual.html>

The latest-and-greatest remains available at the original URL.

But the remaining half I still don’t have a good answer to.  To make the URL above, I’d need to have autoconf generate libxo.3 from libxo.3.in (etc.) and that would be annoying.  I could make a simple file containing only the version number, like:

.ds Vr 0.3.2

and have all the man pages “.so” that file.  This would still be less annoying.

By annoying I mean that testing man page formatting would no longer be “nroff -man $src/libxo/libxo.3 | more”.  I’d have to install them before I could see the output.  Perhaps this is a low standard of “annoying”, but it’s annoying none the less….

Any suggestions?

Thanks,
 Phil

**Comment by brooksdavis** [comment]
Thanks for getting the manpages into the release.  They are now in the port.

I'm not sure the mandoc utility supports .so so that may not be an option.  It seems like .in files wouldn't be that horrible so long as they render properly (modulo the URL) before processing.  Otherwise I might be tempted to have a separate script that updates the version in the manpages and commit the change to the branch before release.

**Comment by philshafer** [comment]
On Apr 27, 2015, at 4:52 PM, Brooks Davis <notifications@github.com> wrote:
> I'm not sure the mandoc utility supports .so so that may not be an option.
> 

Right. I knew freebsd moved to mandoc but wasn’t thinking that would affect this.  Hmm… Looks like there are enough man pages already using .so that it must be supported:

find /usr/share/man/man3 -type f | xargs grep "^\.so" | wc -l
     430

Then again, that was under macosx.
> It seems like .in files wouldn't be that horrible so long as they render properly (modulo the URL) before processing. Otherwise I might be tempted to have a separate script that updates the version in the manpages and commit the change to the branch before release.
> 

Or I could add an install-hook that does something like “sed s/VERSION/${LIBXO_VERSION}/“.

Thanks,
 Phil
