### ISSUE TITLE
Versioned output

### ISSUE THREAD

**Issue by allanjude** [Juniper/libxo#28]
The outputs should be versioned, so if the content ever has to change, parses will be aware of the change.

Adding something like xo_version("version.string.here"); to the output, that is not displayed for the plain text version, but it part of the JSON/XML etc output.

**Comment by philshafer** [comment]
Easy enough to add, and to encode in XML (as an attribute), but the JSON encoding of meta data is always tricky.  There’s no guarantee that the JSON output would be anything more than:

“tag”: “value”

or:

{ “tag”: “value” }

so adding even something simple like “__version”: “version.string.here” feels fragile.  But caveat JSONer.  I’ll try to get it done today.

Thanks,
 Phil

**Comment by philshafer** [comment]
Implemented in 'develop'
