### ISSUE TITLE
xo_humanize.h used in core/test_02.c, but missing from 0.3.5

### ISSUE THREAD

**Issue by brooksdavis** [Juniper/libxo#41]
The file does appear in develop so I assume it's just missing, but removing the include line seems to allow the test to pass.

**Comment by philshafer** [comment]
Are you sure?  I see it here:

https://github.com/Juniper/libxo/tree/develop/libxo <https://github.com/Juniper/libxo/tree/develop/libxo>

Aside from this test, it should only be used when libc lacks humanize().

Thanks,
 Phil

**Comment by brooksdavis** [comment]
It doesn't seem to be in the tarball though.  I'm not sure what's going on
since it does seem to be in git at the same hash.

-- Brooks

**Comment by philshafer** [comment]
This issue is fixed in the new release; "make distcheck" also now works correctly.

Thanks,
 Phil
