### ISSUE TITLE
Better translation support

### ISSUE THREAD

**Issue by davidchisnall** [Juniper/libxo#42]
[ Writing up summary of discussion from the Ottawa departure lounge ]

It would be nice to make the formatting strings more amenable to translation, referring to fields by name and allowing reordering in the translated version.  For example, if I want to print the string:

	Push the red button.

In French this is:

	Poussez le bouton rouge.

I want to translate this in two chunks, because the button colour is locale-dependent.  This is typically done now with gettext as something like:

	printf(_("Push the %s button."), _(red));

This becomes more complex in C if you have multiple formats, because you need to use the `printf` modifies to reorder them.
Languages like Python that have dictionaries as first-class citizens make this a bit easier, by passing a dictionary for the arguments with the format string including them by name.

It would be nice to change the xo_emit() calls to do the next best thing in C, where each of the variadic parameters are pairs of name and format string, followed by the variadic parameter.  For example:

	xo_emit("Push the {colour} button", "color,s", "red");

The translation of the format string would also allow other utilities to do the transformation, for example if we emit HTML, transform it, and then want to translate it at the end of a pipeline.  libxo should assume that all format strings (though probably not all strings that are inserted, unless they have a modifier character) should be translated.

**Comment by philshafer** [comment]
On Jun 17, 2015, at 10:22 AM, davidchisnall <notifications@github.com> wrote:
> It would be nice to make the formatting strings more amenable to translation, referring to fields by name and allowing reordering in the translated version. 

The proposal I sent around last week looks like this:

Add a new role “{G:}” which appears at the start of a format string to tell libxo to look up the string using gettext()
Add a new modifier “{g:}” which looks up the results of the formatting using gettext().

The gettext msgstr would allow name-based substitutions, allowing it to alter the order.

    xo_emit("{G:}My {g:color} {g:pet} is {g:status}\n", "black", "cat", "scared");

The FR.po would have:

    msgid "{G:}My {g:color} {g:pet} is {g:status}\n"
    msgstr "Mon {:pet} {:color} a {:status}\n"

    msgid "cat"
    msgstr "noir"

    msgid "black"
    msgstr "noir"

    msgid "scared"
    msgstr “peur"

I'd have to track each field distinctly and then format them into the output string, and since it would be string copies, I'd ignore any formatting into in the gettext() values, meaning:

   msgstr "Mon {:pet/%4.4s} ..."

would ignore the "4.4" part.

Does this seem reasonable?

Thanks,
 Phil

**Comment by davidchisnall** [comment]
It would sort-of work, but it's still a bit ugly because now you end up with positional modifiers.  This also adds to the maintenance burden (you need to keep track of reorderings every time that you modify the format).  The advantage of the proposal that we came up with in YOW is that you can do the pass over the va_list always getting the type from the previous argument, then build your dictionary and use that for argument insertion.  It would also make the translation strings more readable.  In your example, it would be (assuming that `"g"` implies a `char*` and assuming that the format string is always looked up using gettext, as this behaviour allows you to transparently fall back to just using the original if it doesn't make sense to translate it):

	xo_emit("My {:color} {:pet} is {:status}\n", "color,g", "black", "pet,g", "cat", "status,g", "scared");

The translation strings would then be:

	msgid "My {:color} {:pet} is {:status}\n"
	msgstr "Mon {:pet} {:color} a {:status}\n"

This separates the information that's important to translators (strings with words that are injected) from the information that's important to programmers and libxo (type specifiers, positional arguments).

Another example where this simplifies life is when you want to specify a quantity.  For example, consider this translation:

	msgid "I have {:num} cats"
	msgstr "J'ai {:num} chats"

This doesn't embed anything about the type, I can use it as any of the following:

	short few_cats = ...;
	long long many_cats = ...;
	char *formatted_number_cats = ...;
	/* Only using a short for the number of cats */
	xo_emit("I have {:num} cats}", "num,hd", few_cats);
	/* Maybe some people have more than 2^32 cats? */
	xo_emit("I have {:num} cats}", "num,lld", many_cats);
	/* Perhaps I want to use a text representation for small numbers? */
	xo_emit("I have {:num} cats}", "num,g", formatted_number_cats);
	/* I'm integrating with some legacy thing that has already given me a 
	   localised number as a string, so I want libxo to use this directly. */
	xo_emit("I have {:num} cats}", "num,s", formatted_number_cats);

It should also remove some of the criticism that `xo_emit` is less readable than `printf`, as this separation makes it a lot more readable and means that even in simple tools we get a much cleaner way of doing localisation than using non-libxo functions.

**Comment by philshafer** [comment]
The 'develop' branch has code now that handles gettext:

- {G:} role for gettext on the format string,
- {g:} modifier for gettext on the field value, and
- {p:} modifier for plural support (with or without gettext).

Also formatting information is stripped from msgid strings before look up, making .po files look less ugly.  A "xopo" utility is provided to filter xgettext output to make suitable .pot files.

A few things to note in the following example:
- it refers to a non-default domain ("ldns"); the domain can so be static ("{G:ldns}") or the default ("{G:}")
- The {p:} modifier uses "byte,bytes" as the singular and plural forms.  Add the "{g:} modifier and you get ngettext look up.  {p:} works even when libintl is not found by configure.

```
    xo_emit("{G:/%s}Received {:received/%zu} {Ngp:byte,bytes} "
            "from {:from/%s}#{:port/%d} in {:time/%d} ms\n",
            "ldns", (size_t) 1234, "foop", 4321, 32);
```

plus:

```
msgid "Received {:received} {N:byte,bytes} from {:from}#{:port} in {:time} ms\n"
msgstr "Eceivedray {:received} {N:byte,bytes} omfray {:from}#{:port} inyay {:time} msyay\n"

msgid "byte"
msgid_plural "bytes"
msgstr[0] "ldb0"
msgstr[1] "ldb1"
msgstr[2] "ldb2"
```
yields:

```
Eceivedray 1234 ldb2 omfray foop#4321 inyay 32 msyay
```

Sure, it's a gibberish example, but the plumbing works.  Reordering is supported, but fields are rendered before reordering is performed, allowing consistent key and xpath processing even when the .po file rearranges the keys.  Lots of docs:

https://github.com/Juniper/libxo/blob/develop/doc/libxo.txt#L2891
https://github.com/Juniper/libxo/blob/develop/doc/libxo.txt#L556
https://github.com/Juniper/libxo/blob/develop/doc/libxo.txt#L773
https://github.com/Juniper/libxo/blob/develop/doc/libxo.txt#L876

I haven't cranked a release yet, so these doc links are in raw test format.  Please let me know what you think.  I'd like to make a release in the few couple of days.

Thanks,
 Phil

**Comment by davidchisnall** [comment]
I still much prefer the model where the name and encoding types are moved out to the variadic parameters.  This makes it much easier to see what each means and will also make it easier to provide a libxo interface in languages that have a first-class dictionary type that uses the same format strings as the C version (not to mention making the format strings more human-readable and making it easier to visually check that you have the correct arguments for each type and making it easier to parse...).

**Comment by philshafer** [comment]
I disagree.  Intermixing field names, formatting directions, and content among the argument list will increase complexity, confusion, and opportunity for error.  Replicating the field name in the argument list especially would open us to more errors.  Intermixing the argument name and formatting seems in conflict with the idea of making a pseudo-hash.  The other feature that would be lost is the ability to construct a single field from the multiple arguments, like:

        xo_emit("{keq:sku/%s-%u}{k:name/%-10s}{n:sold/%12u}\n”, ip->i_sku_base, ip->i_sku_num, ip->i_title, ip->i_sold);

Using the formatting string puts the complexity into a single place where it can be more easily managed.  It keeps more consistency with printf() formatting styles that makes conversion to libxo simpler and should reduce errors.  The format string and the function name needs to change, but the rest of the arguments are generally left undisturbed.

Re: other languages; I would see python’s string.format as the model, where the formatting string contains all the details of formatting and the arguments are either a positional or a hash, with each object presenting a consistent interface to the formatter (obj.str()).

Thanks,
 Phil

**Comment by philshafer** [comment]
Added {G:} role and {g:} and {p:} modifiers.  Also added xopo utility to generate/filter messages strings from xgettext into proper format.  Fixed in libxo.0.4.2.
