### ISSUE TITLE
.Nd entries in man pages are not correct for some man pages

### ISSUE THREAD

**Issue by rodrigc** [Juniper/libxo#43]
According to mdoc(7), the ".Nd" macro is:
A one line description of the manual's content.

It looks like the .Nd macro has been cut and paste across several man pages
and is wrong.

./xo_create.3:.Nd emit formatted output based on format string and arguments
./xo_set_flags.3:.Nd emit formatted output based on format string and arguments
./xo_attr.3:.Nd emit formatted output based on format string and arguments
./xo_set_style.3:.Nd emit formatted output based on format string and arguments
./xo_set_info.3:.Nd emit formatted output based on format string and arguments
./xo_set_allocator.3:.Nd emit formatted output based on format string and arguments
./xo_flush.3:.Nd emit formatted output based on format string and arguments
./xo_open_list.3:.Nd emit formatted output based on format string and arguments
./xo_finish.3:.Nd emit formatted output based on format string and arguments
./xo_set_writer.3:.Nd emit formatted output based on format string and arguments
./xo_open_container.3:.Nd emit formatted output based on format string and arguments
./xo_emit.3:.Nd emit formatted output based on format string and arguments

**Comment by philshafer** [comment]
Hmmm…. In contrib/mdocml/mdoc.7, I see:

   Nd
     A one line description of the manual’s content.  This is the mandatory
     last macro of the NAME section and not appropriate for other sections.

     Examples:
           .Nd mdoc language reference
           .Nd format and display UNIX manuals

     The Nd macro technically accepts child macros and terminates with a sub‐
     sequent Sh invocation.  Do not assume this behaviour: some whatis(1)
     database generators are not smart enough to parse more than the line
     arguments and will display macros verbatim.

     See also Nm.

grepping .Nd in various man files should similar usage.

Thanks,
 Phil

**Comment by philshafer** [comment]
Fixed in new release; also fixed multiple .Nd lines per file

Thanks,
 Phil

**Comment by rodrigc** [comment]
Thanks, Phil!
