### ISSUE TITLE
Build broken in many ways for non-default prefix

### ISSUE THREAD

**Issue by davidchisnall** [Juniper/libxo#52]
When configuring with a non-default prefix, the package-config file is not correctly set up (it retains a load of `${}` and `@...@` values, and the `rpath` for the `xo` binary is set so that it can't find the shared library (it looks in `/usr/local/lib`).

**Comment by philshafer** [comment]
The ${var} is valid pkg-config syntax, but the @var@ is not.  I had LIBXO_var in places instead of XO_var.  These are now fixed; also added -I and -L where missing.   Fix is in 'develop' and will be in the next release.

Thanks,
 Phil
