### ISSUE TITLE
Newline before closing brace in json output

### ISSUE THREAD

**Issue by afengler** [Juniper/libxo#62]
libxo seems to be creating a newline before the last closing brace when doing non-pretty json output:

```
% uptime --libxo json
{"uptime-information": {"time-of-day":" 5:03PM","uptime":25201,"days":0,"hours":7,"minutes":0,"seconds":31,"uptime-human":" 7 hrs,","users":9,"load-average-1":0.41,"load-average-5":0.36,"load-average-15":0.34}
}
```

This is manifesting on all libxo tools I've tested on multiple versions of FreeBSD, up to 12-ALPHA6

**Comment by philshafer** [comment]
Yes; easily duplicated.   Thanks...

**Comment by philshafer** [comment]
Fixed in the "develop" branch
