### ISSUE TITLE
FreeBSD's json format prints an unescaped new line before the final closing bracket

### ISSUE THREAD

**Issue by jlduran** [Juniper/libxo#74]
FreeBSD's `--libxo json` format prints an unescaped new line before the final closing bracket.  Here is an example with a short output (`jls` with no jails, any other command will do):

    % jls --libxo json
    {"__version": "2", "jail-information": {"jail": []}
    }

Notice the closing bracket in a new line (unescaped).  The tests in libxo do not seem to include it. I am not sure if this is intended.

**Comment by philshafer** [comment]
Not intentional.  Off hand, that looks like just a bug.

Thanks,
 Phil

**Comment by jlduran** [comment]
This bug is not present in FreeBSD 13.
