### ISSUE TITLE
xo/xo.c#L99: add missing UNUSED marker for all unused flags

### ISSUE THREAD

**Issue by pstef** [Juniper/libxo#85]
int lflag UNUSED = 0;
    int hflag = 0, jflag = 0, tflag = 0,
	zflag = 0, qflag = 0,
are all set but not used, however only lflag is marked as such. Compilers complain :(

**Comment by philshafer** [comment]
Yup, there are all ignored and should be marked as such.  Here’s a patch:

diff --git a/xo/xo.c b/xo/xo.c
index 6d45c9c..e682cbf 100644
--- a/xo/xo.c
+++ b/xo/xo.c
@@ -95,9 +95,10 @@ static xo_ssize_t
 formatter (xo_handle_t *xop, char *buf, xo_ssize_t bufsiz,
 	   const char *fmt, va_list vap UNUSED)
 {
-    int lflag UNUSED = 0;	/* Parse long flag, though currently ignored */
-    int hflag = 0, jflag = 0, tflag = 0,
-	zflag = 0, qflag = 0, star1 = 0, star2 = 0;
+    /* printf-style formatting flags, currently ignored */
+    int lflag UNUSED = 0, hflag UNUSED = 0, jflag UNUSED = 0,
+	tflag UNUSED = 0, zflag UNUSED = 0, qflag UNUSED = 0;
+    int star1 = 0, star2 = 0;
     int rc = 0;
     int w1 = 0, w2 = 0;
     const char *cp;

Could you please let me know the compiler/version that is failing?

Thanks,
 Phil

**Comment by pstef** [comment]
The patch looks good to me, but I didn't test it.
Sorry, I didn't mean to suggest that a compiler is failing. clang/llvm 13 was recently imported into base and by default it warns about variables set but not used.

**Comment by pstef** [comment]
Fixed in de776ab1a8985fbeb510af8e39777fa9db69d3d9
